apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resource-quota
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
